sources:
  owncast_api:
    default_hostname: localhost:8080
    repo_url: https://github.com/owncast/owncast
    # pinned to master HEAD as of 2026-07-26; bump when upgrading
    pinned_tag: 4d04992fad51cceca206b71f24d129cfe7dcc90e
    backend: openapi3
    openapi3:
      files:
        - openapi.yaml
